// nx-domain-angular/apps/modulereact/src/app/parcel.tsx
import React from 'react';
import ReactDOM from 'react-dom';
import singleSpaReact from 'single-spa-react';

function ParcelComponent(props: any) {
  return (
    <section>
      Parcel component with {props.name} is mounted!
      <br />
      Passed props from Parent
      <div style={{ color: 'red' }}>{props.customProp1}</div>
    </section>
  );
}

const lifecycles = singleSpaReact({
  React,
  ReactDOM,
  rootComponent: ParcelComponent,
  errorBoundary(err, info, props) {
    // Customize the root error boundary for your microfrontend here.
    return <div>Error</div>;
  },
});

export const name = 'react-parcel';
export const { bootstrap, mount, unmount } = lifecycles;

// nx-domain-angular/apps/moduleangular1/src/app/parcel.component.ts
import { Component } from '@angular/core';
import { singleSpaPropsSubject } from '../single-spa/single-spa-props';

@Component({
  selector: 'app-parcel',
  template: `<section>
    <!-- Angular Parcel component is mounted! -->
    Parcel component with {{ (props$ | async)?.name }} is mounted!
    <br />
    Passed props from Parent
    <div style="color: red">{{ (props$ | async)?.customProp1 }}</div>
  </section> `,
})
export class ParcelComponent {
  public props$ = singleSpaPropsSubject;
  title = 'angular-parcel';
}
